// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLiaNDWEoZN4Nzu9nj1Rf5HLYoN3EQGoI',
    appId: '1:671632150189:web:5eec980267029f7ad18024',
    messagingSenderId: '671632150189',
    projectId: 'appmedi-d2168',
    authDomain: 'appmedi-d2168.firebaseapp.com',
    storageBucket: 'appmedi-d2168.appspot.com',
    measurementId: 'G-NC5DGNGC8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzEuH103QfN01MM0AOTvQNjZWlfPPxUkI',
    appId: '1:671632150189:android:419c85b23113b26cd18024',
    messagingSenderId: '671632150189',
    projectId: 'appmedi-d2168',
    storageBucket: 'appmedi-d2168.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJvxdXY3mgptvwEfSwUh1z7zmXLJnHGHU',
    appId: '1:671632150189:ios:0c1adb55fbc5b078d18024',
    messagingSenderId: '671632150189',
    projectId: 'appmedi-d2168',
    storageBucket: 'appmedi-d2168.appspot.com',
    iosClientId: '671632150189-6ckg6v4aqmj4u0n1hk609kca8b19s0is.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMedi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJvxdXY3mgptvwEfSwUh1z7zmXLJnHGHU',
    appId: '1:671632150189:ios:2d840dad9fabcdecd18024',
    messagingSenderId: '671632150189',
    projectId: 'appmedi-d2168',
    storageBucket: 'appmedi-d2168.appspot.com',
    iosClientId: '671632150189-nqn7ffnr3gpoabsqq767cgi2o9i3ml0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMedi.RunnerTests',
  );
}
