/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MediIcons {
  MediIcons._();

  static const _kFontFam = 'MediIcons';
  static const String? _kFontPkg = null;

  static const IconData edit = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach_circled = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_2 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_circled = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circled = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circled2 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circled = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_list = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_new = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_open = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_open = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_open = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_open = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData universal_access = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blind = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address_book = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_alt = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_wink = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_wink2 = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_unhappy = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_sleep = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_coffee = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_sunglasses = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin3 = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin4 = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin5 = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin6 = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medical_pack = IconData(0xea3d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xf004, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_1 = IconData(0xf007, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_ul = IconData(0xf0ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_md = IconData(0xf0f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ambulance = IconData(0xf0f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medkit = IconData(0xf0fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard = IconData(0xf11c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_plus = IconData(0xf271, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase_medical = IconData(0xf469, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData capsules = IconData(0xf46b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_medical = IconData(0xf477, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_medical_alt = IconData(0xf478, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData first_aid = IconData(0xf479, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_tag = IconData(0xf507, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope_open_text = IconData(0xf658, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
